name: readthedocs
channels:
  - conda-forge
dependencies:
  - python=3.8
  - graph-tool==2.31
  - pip:
    - dask[complete]>=2.30.0
    - jupyter==1.0.0
    - numba>=0.50.1
    - pymatgen==2021.2.8
    - tqdm>=4.56.0
